# name of conda environment
name: pdb_prot_align

# channels to install conda dependencies
channels:
  - conda-forge
  - bioconda

# conda dependencies
dependencies:
  - pip
  - mafft
  # list packages to install with pip
  - pip:
    - .
