# name of conda environment
name: pdb_prot_align

# channels to install conda dependencies
channels:
  - conda-forge
  - bioconda

# conda dependencies
dependencies:
  - python=3.7
  - pip
  - mafft=7.407
  # list packages to install with pip
  - pip:
    - .
